version: '3.3'
services:  
 base-image: 
  image: base-image
  build: 
   context: .

 rides: 
  image: rides
  volumes:
   - ./:/home
  container_name: rides
  build: 
   context: .
   dockerfile: rides_dockerfile
  ports: 
   - 80:80
  networks: 
   microservice_nets: 
    ipv4_address: 172.16.238.11


networks:
 microservice_nets:
  ipam:
   driver: default
   config:
    - subnet: "172.16.238.0/24"
